# Generated by Django 3.0 on 2020-01-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20200110_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='think_analytics',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='think_analytics',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='think_analytics',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
